version: '3.8'
services:
  db:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example_root_pass
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nc_user
      MYSQL_PASSWORD: nc_pass
    volumes:
      - db_data:/var/lib/mysql

  nextcloud:
    image: nextcloud:latest
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nc_user
      MYSQL_PASSWORD: nc_pass
    volumes:
      - nextcloud_data:/var/www/html

  onlyoffice:
    image: onlyoffice/documentserver:latest
    depends_on:
      - nextcloud
    ports:
      - "8081:80"
    restart: unless-stopped
    environment:
      JWT_ENABLED: "false"

volumes:
  db_data:
  nextcloud_data:
