version: "3.8"

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nc_user
      - POSTGRES_PASSWORD=nc_pass

  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nc_user
      - POSTGRES_PASSWORD=nc_pass
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=ChangeMe123!
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost

  collabora:
    image: collabora/code:latest
    restart: unless-stopped
    cap_add:
      - MKNOD
    environment:
      - domain=localhost
      - extra_params=--o:ssl.enable=false
    ports:
      - "9980:9980"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
    ports:
      - "8081:8080"

  moodle:
    image: bitnami/moodle:latest
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=moodle123
      - MOODLE_SITE_NAME=Цифровая Платформа
    depends_on:
      - db

  gitea:
    image: gitea/gitea:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - gitea_data:/data

  nexus:
    image: sonatype/nexus3:latest
    restart: unless-stopped
    ports:
      - "8083:8081"
    volumes:
      - nexus-data:/nexus-data

  jitsi:
    image: jitsi/web:latest
    restart: unless-stopped
    ports:
      - "8443:443"

  openldap:
    image: osixia/openldap:latest
    restart: unless-stopped
    environment:
      - LDAP_ORGANISATION=PesPlatform
      - LDAP_DOMAIN=pes.local
      - LDAP_ADMIN_PASSWORD=ldap123
    ports:
      - "389:389"
      - "636:636"

volumes:
  gitea_data:
  nexus-data:
